name: train_random_forest
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pandas=1.4.2
  - pip=22.1.2
  - mlflow=1.14.1
  - scikit-learn=1.1.1
  - matplotlib=3.2.2
  - pillow=9.1.1
  - pip:
      - wandb==0.12.19
